name: Lxs
bio: 'Welcome to my blog!'
picture: 'src/images/profile.jpg'

url: http://liuxiaoshuang.com
permalink: /:title/

analytics: 'UA-MYANALYTICS'

email: myemail@gmail.com

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor]

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com
