# Site settings
title: 刘晓双
description: Welcome! This is Xiaoshuang's blog.
keywords: Life, Machine Learning, BIT
author: Lxs
baseurl: "" # the subpath of your site, e.g. /blog/
url: "liuxiaoshuang.com" # the base hostname & protocol for your site
